// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2UmcDFNv0sIpgj5W5kCGHBFb_1z2I0Ls',
    appId: '1:673005324146:android:1ba6252d5ee3c5fcc83feb',
    messagingSenderId: '673005324146',
    projectId: 'olympialaiset-5e33c',
    storageBucket: 'olympialaiset-5e33c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ34RA82NKIzPGdVeoqMafO8qA7yBP9QI',
    appId: '1:673005324146:ios:a02a1a7c69362aa0c83feb',
    messagingSenderId: '673005324146',
    projectId: 'olympialaiset-5e33c',
    storageBucket: 'olympialaiset-5e33c.appspot.com',
    iosClientId: '673005324146-45om7fc7tjo6988ffajsa9r8nf9oku01.apps.googleusercontent.com',
    iosBundleId: 'com.example.flappyBird',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ34RA82NKIzPGdVeoqMafO8qA7yBP9QI',
    appId: '1:673005324146:ios:a02a1a7c69362aa0c83feb',
    messagingSenderId: '673005324146',
    projectId: 'olympialaiset-5e33c',
    storageBucket: 'olympialaiset-5e33c.appspot.com',
    iosClientId: '673005324146-45om7fc7tjo6988ffajsa9r8nf9oku01.apps.googleusercontent.com',
    iosBundleId: 'com.example.flappyBird',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApLpLvzJgRu_7UtnheUFZxEdFuN1kB6d4',
    appId: '1:673005324146:web:c6303e3fde823316c83feb',
    messagingSenderId: '673005324146',
    projectId: 'olympialaiset-5e33c',
    authDomain: 'olympialaiset-5e33c.firebaseapp.com',
    storageBucket: 'olympialaiset-5e33c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApLpLvzJgRu_7UtnheUFZxEdFuN1kB6d4',
    appId: '1:673005324146:web:a49c3c9936dd99b6c83feb',
    messagingSenderId: '673005324146',
    projectId: 'olympialaiset-5e33c',
    authDomain: 'olympialaiset-5e33c.firebaseapp.com',
    storageBucket: 'olympialaiset-5e33c.appspot.com',
  );

}