name: flappy_bird_game
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  flame: ^1.10.0
  flame_audio: ^2.1.2
  image_picker: ^1.0.5
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.1.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/audio/

  fonts:
    - family: Game     
      fonts:
        - asset: assets/fonts/Game.ttf