// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRgqgo3IPbjD583jqaK6VhzUOffMDZu_k',
    appId: '1:151528414069:android:711c6fa23cd481e09f913c',
    messagingSenderId: '151528414069',
    projectId: 'taloyhtio-app-cdb6b',
    databaseURL: 'https://taloyhtio-app-cdb6b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taloyhtio-app-cdb6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrY9UrTWw1-7hB-cWLDMDAAAeZkWnKLNE',
    appId: '1:151528414069:ios:979e584761b0e28d9f913c',
    messagingSenderId: '151528414069',
    projectId: 'taloyhtio-app-cdb6b',
    databaseURL: 'https://taloyhtio-app-cdb6b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taloyhtio-app-cdb6b.appspot.com',
    androidClientId: '151528414069-o28fiuki3duagc5q3ruf6i61v4ja4m0g.apps.googleusercontent.com',
    iosClientId: '151528414069-aqa8oel2dbjrveu6vplpag9k55k8o7ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.naytto',
  );
}
